version: "3.8"

services:
  front_envoy:
    build:
      context: .
      dockerfile: docker/front-envoy/Dockerfile
    ports:
      - "3000:3000"
      - "9901:9901"
  auth_data_envoy:
    build:
      context: .
      dockerfile: docker/auth-data-envoy/Dockerfile
    hostname: auth.data.envoy
    ports:
      - "3001:3001"
      - "9902:9902"
  opa:
    build:
      context: .
      dockerfile: ./docker/opa/Dockerfile
    ports:
      - "4000:4000"
      - "8182:8181"
  opal_server:
    image: permitio/opal-server:latest
    environment:
      - UVICORN_NUM_WORKERS=1
      - OPAL_POLICY_REPO_URL=https://github.com/hyt-sasaki/opal_policies.git
      - OPAL_POLICY_REPO_MAIN_BRANCH=main
      - OPAL_DATA_CONFIG_SOURCES={"config":{"entries":[{"url":"http://auth.data.envoy:3001/auth/data","topics":["policy_data"],"dst_path":"/custom_info"}]}}
      - OPAL_LOG_FORMAT_INCLUDE_PID=true
      - OPAL_POLICY_REPO_POLLING_INTERVAL=300
    ports:
      - "7002:7002"
    depends_on:
      - auth_data_envoy
  opal_client:
    build:
      context: .
      dockerfile: ./docker/opal-client/Dockerfile
    environment:
      - OPAL_SERVER_URL=http://opal_server:7002
      - OPAL_POLICY_STORE_URL=http://opa:8181
      - OPAL_LOG_FORMAT_INCLUDE_PID=true
      - OPAL_INLINE_OPA_LOG_FORMAT=http
      - OPAL_OFFLINE_MODE_ENABLED=true
    volumes:
      - opa_backup:/opal/backup:rw

    ports:
      # exposes opal client on the host machine, you can access the client at: http://localhost:7766
      - "7766:7000"
      # exposes the OPA agent (being run by OPAL) on the host machine
      # you can access the OPA api that you know and love at: http://localhost:8181
      # OPA api docs are at: https://www.openpolicyagent.org/docs/latest/rest-api/
      - "8181:8181"
    depends_on:
      - opal_server
    # this command is not necessary when deploying OPAL for real, it is simply a trick for dev environments
    # to make sure that opal-server is already up before starting the client.
    command: sh -c "exec ./wait-for.sh opal_server:7002 --timeout=20 -- ./start.sh"
  jaeger:
    image: "jaegertracing/all-in-one:latest"
    ports:
      - "16686:16686"
      - "14268"
      - "14250"
    environment:
      - COLLECTOR_OTLP_ENABLED=true
  otel_collector:
    build:
      context: .
      dockerfile: ./docker/otel-collector/Dockerfile
    restart: always
    command: [ "--config=/etc/otel-collector-config.yaml", "" ]
    ports:
      - "4317:4317"
volumes:
  opa_backup: