spring:
  datasource:
    url: ${MYSQL_URL:jdbc:mysql://localhost:3306/sample?allowPublicKeyRetrieval=true&useSSL=false}
    username: ${MYSQL_USER_NAME:docker}
    password: ${MYSQL_PASSWORD:docker}
    hikari:
      leak-detection-threshold: 5000
  jooq:
    sql-dialect: mysql