plugins:
  envoy_ext_authz_grpc:
    addr: :4000
    path: http/api/authz/allow

decision_logs:
  console: true

status:
  prometheus: true

distributed_tracing:
  type: grpc
  address: otel.collector:4317
  service_name: opa
  sample_percentage: 100
  encryption: "off"