application_log_config:
  log_format:
    json_format:
      Timestamp: "%Y-%m-%dT%T.%F"
      ThreadId: "%t"
      SourceLine: "%s:%#"
      Level: "%l"
      LoggerName: "%n"
      Message: "%j"
      LogType: "application_log"
admin:
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 9901
  access_log:
    - name: envoy.access_loggers.stdout
      typed_config:
        "@type": type.googleapis.com/envoy.extensions.access_loggers.stream.v3.StdoutAccessLog
        log_format:
          json_format:
            Timestamp: "%START_TIME(%Y-%m-%dT%T.%F)%"
            Method: "%REQ(:METHOD)%"
            Path: "%REQ(X-ENVOY-ORIGINAL-PATH?:PATH)%"
            StatusCode: "%RESPONSE_CODE%"
            Duration: "%DURATION%"
            LogType: "admin_access_log"
static_resources:
  listeners:
    - name: listener_0
      address:
        socket_address:
          address: 0.0.0.0
          port_value: 3000
      filter_chains:
        - filters:
            - name: envoy.filters.network.http_connection_manager
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                stat_prefix: ingress_http
                codec_type: AUTO
                generate_request_id: true
                tracing:
                  provider:
                    name: envoy.tracers.opentelemetry
                    typed_config:
                      "@type": type.googleapis.com/envoy.config.trace.v3.OpenTelemetryConfig
                      grpc_service:
                        envoy_grpc:
                          cluster_name: opentelemetry_collector
                        timeout: 0.250s
                      service_name: frontend-proxy
                route_config:
                  name: local_route
                  virtual_hosts:
                    - name: api_service
                      domains:
                        - "*"
                      routes:
                        - match:
                            prefix: "/"
                          route:
                            cluster: api_cluster
                access_log:
                  - name: access_log
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.access_loggers.open_telemetry.v3.OpenTelemetryAccessLogConfig
                      common_config:
                        log_name: "front-envoy-access-log"
                        grpc_service:
                          envoy_grpc:
                            cluster_name: opentelemetry_collector
                          timeout: 0.25s
                        transport_api_version: V3
                      attributes:
                        values:
                          - key: "x-request-id"
                            value:
                              string_value: "%REQ(X-REQUEST-ID)%"
                          - key: "method"
                            value:
                              string_value: "%REQ(:METHOD)%"
                          - key: "x-envoy-original-path"
                            value:
                              string_value: "%REQ(X-ENVOY-ORIGINAL-PATH?:PATH)%"
                          - key: "authority"
                            value:
                              string_value: "%REQ(:AUTHORITY)%"
                          - key: "protocol"
                            value:
                              string_value: "%PROTOCOL%"
                          - key: "response_code"
                            value:
                              string_value: "%RESPONSE_CODE%"
                          - key: "response_code_details"
                            value:
                              string_value: "%RESPONSE_CODE_DETAILS%"
                          - key: "upstream_host"
                            value:
                              string_value: "%UPSTREAM_HOST%"
                          - key: "duration"
                            value:
                              string_value: "%DURATION%"
                          - key: "upstream_local_address"
                            value:
                              string_value: "%UPSTREAM_LOCAL_ADDRESS%"
                          - key: "upstream_remote_address"
                            value:
                              string_value: "%UPSTREAM_REMOTE_ADDRESS%"
                          - key: "upstream_transport_failure_reason"
                            value:
                              string_value: "%UPSTREAM_TRANSPORT_FAILURE_REASON%"
                          - key: "downstream_transport_failure_reason"
                            value:
                              string_value: "%DOWNSTREAM_TRANSPORT_FAILURE_REASON%"
                          - key: "LogType"
                            value:
                              string_value: "listener_access_log"
                http_filters:
                  - name: envoy.filters.http.ext_authz
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.ext_authz.v3.ExtAuthz
                      grpc_service:
                        envoy_grpc:
                          cluster_name: authorizer
                        timeout: 30s
                      transport_api_version: V3
                  - name: envoy.filters.http.router
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
  
  clusters:
    - name: api_cluster
      connect_timeout: 0.25s
      type: STRICT_DNS
      lb_policy: ROUND_ROBIN
      load_assignment:
        cluster_name: api_cluster
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: host.docker.internal
                      port_value: 8080
    - name: authorizer
      type: STRICT_DNS
      typed_extension_protocol_options:
        envoy.extensions.upstreams.http.v3.HttpProtocolOptions:
          "@type": type.googleapis.com/envoy.extensions.upstreams.http.v3.HttpProtocolOptions
          explicit_http_config:
            http2_protocol_options: { }
      lb_policy: ROUND_ROBIN
      load_assignment:
        cluster_name: authorizer
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address: { address: opa, port_value: 4000 }
    - name: opentelemetry_collector
      type: STRICT_DNS
      lb_policy: ROUND_ROBIN
      typed_extension_protocol_options:
        envoy.extensions.upstreams.http.v3.HttpProtocolOptions:
          '@type': type.googleapis.com/envoy.extensions.upstreams.http.v3.HttpProtocolOptions
          explicit_http_config:
            http2_protocol_options: { }
      load_assignment:
        cluster_name: opentelemetry_collector
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: otel.collector
                      port_value: 4317